variables:
  GIT_STRATEGY: fetch
  PACKAGE_NAME: PyAnalysisTools
  CI_WEBSITE_DIR: "docs/build"
  DFS_WEBSITE_NAME: "pyanalysistoolsdocs"

stages:
  - test
  - build
  - deploy
  

build_docs:
  image: atlas/analysisbase:latest
  stage: build
  before_script:
    - source /home/atlas/release_setup.sh
    - which python
    - which pip
    - pip install sphinx --user
    - export PATH=/home/atlas/.local/bin:$PATH
  script:
    - ls
    - sphinx-build docs/source/ docs/build/
    - ls docs/build
  artifacts:
    paths:
      - docs/build
    
.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  tags:
    - docker
  script:
    - SMB_PROTOCOL=smb3
    - deploy-dfs

deploy_production:
  variables:
  <<: *deploy_definition
  only:
    - master
  environment:
    name: production
    url: https://cern.ch/PyAnalysisToolsDocs

    
unittest:
  image: atlas/analysisbase:latest
  stage: test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
  before_script:
    - source /home/atlas/release_setup.sh
    - pip install nose --user
    - pip install oyaml --user
    - pip install coverage --user
    - pip install nosedep --user
    - pip install mock --user
    - pip install pathos --user
    - export PATH=$PATH:/home/atlas/.local/bin
  script:
    - nosetests tests.unit --with-coverage

integrationtest:
  image: atlas/analysisbase:latest
  stage: test
  before_script:
    - source /home/atlas/release_setup.sh
    - pip install nose --user
    - pip install oyaml --user
    - pip install coverage --user
    - pip install nosedep --user
    - pip install mock --user
    - pip install pathos --user
    - export PATH=$PATH:/home/atlas/.local/bin
  script:
    - echo $SERVICE_PASS | kinit $CERN_USER
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/CIfiles/PyAnalysisTools/integration/ntuple-311331_0.MC16d.root ${SRC_DIR_ABS}/tests/integration/fixtures/files
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/CIfiles/PyAnalysisTools/integration/ntuple-data18_13TeV_periodO_0.root ${SRC_DIR_ABS}/tests/integration/fixtures/files
    - nosetests tests.integration

style_check:
  image: atlas/analysisbase:latest
  stage: test
  before_script:
    - source /home/atlas/release_setup.sh
    - which python
    - which pip
    - pip install --user flake8==3.5.0
    - export PATH=$PATH:/home/atlas/.local/bin
  script:
    - flake8 .
  allow_failure: true
