variables:
  GIT_STRATEGY: fetch
  PACKAGE_NAME: PyAnalysisTools
  CI_WEBSITE_DIR: "docs/build"
  DFS_WEBSITE_NAME: "pyanalysistoolsdocs"
  DFS_WEBSITE_USERNAME: morgens
  pull_policy: "if-not-present"
stages:
  - build
  - test
  - docs
  - deploy

build_latest_image:
  stage: build
  variables:
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    DOCKER_FILE: Dockerfile
  except:
    - tags
  tags:
    - docker-image-build
  script:
    - ignore

build_docs:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  stage: docs
  before_script:
    - source /home/atlas/release_setup.sh
    - export PATH=/home/atlas/.local/bin:$PATH
    - pip install sphinx --user
  script:
    - ls
    - sphinx-build docs/source/ docs/build/
    - ls docs/build
  artifacts:
    paths:
      - docs/build
    
.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  tags:
    - docker
  script:
    - SMB_PROTOCOL=smb3
    - deploy-dfs

deploy_production:
  variables:
  <<: *deploy_definition
  only:
    - master
  environment:
    name: production
    url: https://cern.ch/PyAnalysisToolsDocs
    
unittest:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  stage: test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
  before_script:
    - source /home/atlas/release_setup.sh
    - export PATH=$PATH:/home/atlas/.local/bin
  script:
    - echo $SERVICE_PASS | kinit $CERN_USER
    - mkdir -p tests/unit/fixtures/files/
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/analysis_files/fixtues/ntuple-311331_0.MC16d.root tests/unit/fixtures/files/
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/analysis_files/fixtues/410470_1.MC16e_NonPrompt.json tests/unit/fixtures/files/
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/analysis_files/fixtues/410470_1.MC16e_Prompt.json tests/unit/fixtures/files/
    - sudo chown atlas run_scripts/*
    - source setup.sh
    - nosetests -w tests/unit --with-coverage --nologcapture --cover-package PyAnalysisTools

unittest_py3:
  image: morgens/root-py3
  stage: test
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
  before_script:
     - pip3 install --user -r requirements.txt
     - export PATH=$PATH:/home/tester/.local/bin
     - export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
  script:
    - echo $SERVICE_PASS | kinit $CERN_USER
    - mkdir -p tests/unit/fixtures/files/
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/analysis_files/fixtues/ntuple-311331_0.MC16d.root tests/unit/fixtures/files/
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/analysis_files/fixtues/410470_1.MC16e_NonPrompt.json tests/unit/fixtures/files/
    - xrdcp -f root://eosuser.cern.ch//eos/user/m/morgens/analysis_files/fixtues/410470_1.MC16e_Prompt.json tests/unit/fixtures/files/
    - sudo chown tester run_scripts/*
    - source setup.sh
    - nosetests -w tests/unit --with-coverage --nologcapture --cover-package PyAnalysisTools

style_check:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  stage: test
  before_script:
    - source /home/atlas/release_setup.sh
    - pip install --user configparser==3.5.1
    - export PATH=$PATH:/home/atlas/.local/bin
  script:
    - flake8 .
  allow_failure: true
