variables:
  GIT_STRATEGY: fetch
  PACKAGE_NAME: PyAnalysisTools

stages:
  - docker
  - trigger

trigger_LQ:
  stage: trigger
  image: appropriate/curl
  script:
    - curl -X POST -F token=$CI_JOB_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/44641/trigger/pipeline

build_image:
  stage: docker
  except:
    - tags
  tags:
    - docker-image-build
  script:
    - ignore

build_tagged_image:
  stage: docker
  variables:
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - docker-image-build
  script:
    - ignore