variables:
  GIT_STRATEGY: fetch
  PACKAGE_NAME: PyAnalysisTools

stages:
  #- docker
  #- trigger
  #- test
  - docs
#   - coverage
  

# trigger_LQ:
#   stage: trigger
#   image: appropriate/curl
#   script:
#     - curl -X POST -F token=$CI_JOB_TOKEN -F ref=master https://gitlab.cern.ch/api/v4/projects/44641/trigger/pipeline

build_docs:
  stage: docs
  before_script:
    - pip install sphinx --user
  script:
    - ls
    - sphinx-build docs/source/ docs/build/
    
    
# test:
#  image: atlas/analysisbase:latest
#   stage: test
#   coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
#   before_script:
#     - source /home/atlas/release_setup.sh
#     - which python
#     - which pip
#     - pip install nose --user
#     - pip install oyaml --user
#     - pip install coverage --user
#     - export PATH=$PATH:/home/atlas/.local/bin
#   script:
#     - nosetests tests.TestLogger --with-coverage

# coverage:
#     stage: coverage
#     script:
#         - nosetests -c .noserc -q --cover-html-dir=build --cover-html
#         - coverage report -m
#     coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
#     artifacts:
#         paths:
#             - build
#         expire_in: 1 day    
# build_image:
#   stage: docker
#   except:
#     - tags
#   tags:
#     - docker-image-build
#   script:
#     - ignore

# build_tagged_image:
#   stage: docker
#   variables:
#     TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   only:
#     - tags
#   tags:
#     - docker-image-build
#   script:
#     - ignore
    
