# GitLab Continuous Integration configuration for the repository.

# "Global" build stages.
stages:
  - package
  - docker
  - run
  - release

# Set the behaviour of the CI build.
variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

# Configuration for the CMake build jobs:
package:
  stage: package
  tags:
    - docker
  image: atlas/analysisbase:21.2.19
  before_script:
    - source /home/atlas/release_setup.sh
  script:
    - source setup.sh

# Setup for building a Docker image from the repository's compiled code.
docker:
  stage: docker
  tags:
    - docker-image-build
  dependencies:
    - package
  script: echo
  variables:
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME