outline: "hist"
stat_box: False
weight: None
normalise: False
dist: None
merge: True
no_data: False
ignore_style: False
style: None
rebin: None
ratio: None
ignore_rebin: False
enable_legend: False
blind: None
legend_options: dict()
make_plot_book: False
is_multidimensional: False
ordering: None
yscale: 1.2
yscale_log: 100.
ymin: 0.1
xmin: None
draw_option: None
ymax: None
is_common: False
normalise_range: None
ratio_config: None
grid: False
logy: False
logx: False
logz: False
signal_scale: None
Lumi: 1.
signal_extraction: True
xtitle: None
ytitle: None
ztitle: None
title: ""
merge_mc_campaigns: True
total_lumi: None
watermark: "Internal"
watermark_size: 0.065
watermark_offset: 0.12
watermark_x: 0.2
watermark_y: 0.86
watermark_size_ratio: 0.04875
watermark_offset_ratio: 0.12
watermark_x_ratio: 0.2
watermark_y_ratio: 0.88
decor_text: None
decor_text_x: 0.2
decor_text_y: 0.8
decor_text_size: 0.05
lumi_text_x: 0.2
lumi_text_y: 0.8
lumi_text_size: 0.05
lumi_text_x_ratio: 0.2
lumi_text_y_ratio: 0.835
lumi_text_size_ratio: 0.0375
xtitle_offset: None
ytitle_offset: None
ztitle_offset: None
xtitle_size: None
ytitle_size: None
axis_labels: None
ztitle_size: None
labels: None
color: None
